/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradingRouteImport } from './routes/trading'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as GamificationRouteImport } from './routes/gamification'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as BehavioralRouteImport } from './routes/behavioral'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetSymbolRouteImport } from './routes/asset.$symbol'
import { Route as ApiInsightRouteImport } from './routes/api/insight'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiMarketRefreshRouteImport } from './routes/api/market/refresh'

const TradingRoute = TradingRouteImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const GamificationRoute = GamificationRouteImport.update({
  id: '/gamification',
  path: '/gamification',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const BehavioralRoute = BehavioralRouteImport.update({
  id: '/behavioral',
  path: '/behavioral',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetSymbolRoute = AssetSymbolRouteImport.update({
  id: '/asset/$symbol',
  path: '/asset/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInsightRoute = ApiInsightRouteImport.update({
  id: '/api/insight',
  path: '/api/insight',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketRefreshRoute = ApiMarketRefreshRouteImport.update({
  id: '/api/market/refresh',
  path: '/api/market/refresh',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/behavioral': typeof BehavioralRoute
  '/docs': typeof DocsRoute
  '/gamification': typeof GamificationRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
  '/trading': typeof TradingRoute
  '/api/chat': typeof ApiChatRoute
  '/api/insight': typeof ApiInsightRoute
  '/asset/$symbol': typeof AssetSymbolRoute
  '/api/market/refresh': typeof ApiMarketRefreshRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/behavioral': typeof BehavioralRoute
  '/docs': typeof DocsRoute
  '/gamification': typeof GamificationRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
  '/trading': typeof TradingRoute
  '/api/chat': typeof ApiChatRoute
  '/api/insight': typeof ApiInsightRoute
  '/asset/$symbol': typeof AssetSymbolRoute
  '/api/market/refresh': typeof ApiMarketRefreshRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/behavioral': typeof BehavioralRoute
  '/docs': typeof DocsRoute
  '/gamification': typeof GamificationRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
  '/trading': typeof TradingRoute
  '/api/chat': typeof ApiChatRoute
  '/api/insight': typeof ApiInsightRoute
  '/asset/$symbol': typeof AssetSymbolRoute
  '/api/market/refresh': typeof ApiMarketRefreshRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/behavioral'
    | '/docs'
    | '/gamification'
    | '/portfolio'
    | '/settings'
    | '/trading'
    | '/api/chat'
    | '/api/insight'
    | '/asset/$symbol'
    | '/api/market/refresh'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/behavioral'
    | '/docs'
    | '/gamification'
    | '/portfolio'
    | '/settings'
    | '/trading'
    | '/api/chat'
    | '/api/insight'
    | '/asset/$symbol'
    | '/api/market/refresh'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/behavioral'
    | '/docs'
    | '/gamification'
    | '/portfolio'
    | '/settings'
    | '/trading'
    | '/api/chat'
    | '/api/insight'
    | '/asset/$symbol'
    | '/api/market/refresh'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BehavioralRoute: typeof BehavioralRoute
  DocsRoute: typeof DocsRoute
  GamificationRoute: typeof GamificationRoute
  PortfolioRoute: typeof PortfolioRoute
  SettingsRoute: typeof SettingsRoute
  TradingRoute: typeof TradingRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiInsightRoute: typeof ApiInsightRoute
  AssetSymbolRoute: typeof AssetSymbolRoute
  ApiMarketRefreshRoute: typeof ApiMarketRefreshRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trading': {
      id: '/trading'
      path: '/trading'
      fullPath: '/trading'
      preLoaderRoute: typeof TradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gamification': {
      id: '/gamification'
      path: '/gamification'
      fullPath: '/gamification'
      preLoaderRoute: typeof GamificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/behavioral': {
      id: '/behavioral'
      path: '/behavioral'
      fullPath: '/behavioral'
      preLoaderRoute: typeof BehavioralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset/$symbol': {
      id: '/asset/$symbol'
      path: '/asset/$symbol'
      fullPath: '/asset/$symbol'
      preLoaderRoute: typeof AssetSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/insight': {
      id: '/api/insight'
      path: '/api/insight'
      fullPath: '/api/insight'
      preLoaderRoute: typeof ApiInsightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/refresh': {
      id: '/api/market/refresh'
      path: '/api/market/refresh'
      fullPath: '/api/market/refresh'
      preLoaderRoute: typeof ApiMarketRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BehavioralRoute: BehavioralRoute,
  DocsRoute: DocsRoute,
  GamificationRoute: GamificationRoute,
  PortfolioRoute: PortfolioRoute,
  SettingsRoute: SettingsRoute,
  TradingRoute: TradingRoute,
  ApiChatRoute: ApiChatRoute,
  ApiInsightRoute: ApiInsightRoute,
  AssetSymbolRoute: AssetSymbolRoute,
  ApiMarketRefreshRoute: ApiMarketRefreshRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
